[general]
import = [
    "~/.config/alacritty/themes/themes/one_dark.toml"
]

[font]
# normal = { family = "JetBrains Mono Nerd Font", style = "Regular" }
normal = { family = "Iosevka NF", style = "Regular" }
size = 18

[window]
opacity = 1
padding = {x = 5, y = 5}

[mouse]

