#################################
#       General Settings        #
#################################
backend = "glx";
experimental-backends = true;
vsync = true;
dithered-present = true;

# Fading
fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-delta = 3;

# Rounded corners
corner-radius = 15;
rounded-corners-exclude = ["class_g = 'Polybar'",
                          "class_g = 'Rofi'",
                          "class_g = 'Dunst'",
                          "window_type = 'tooltip'"
                          ]
