map Z shell 7z a %f.zip %s
map X shell 7z x %f
map gof cd /home/angel/Documents/ofc_demo_2025
map gict cd /home/angel/Documents/ict_open_2025
map gdsd cd /home/angel/Documents/dsd_paper
map gint cd /home/angel/Documents/LINT_Tofino
map gjp cd /home/angel/Documents/journal_paper
default_linemode devicons
